<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Hosts</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.source.hosts-file</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.source.hosts-file</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[\d|\.]+</string>
			<key>name</key>
			<string>constant.source.hosts-file</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.hosts-file</string>
	<key>uuid</key>
	<string>6CDFD93D-9DF1-4F05-A9D1-77EDBB4F0B75</string>
</dict>
</plist>
